### ISSUE TITLE
Switch is not visible

### ISSUE THREAD

**Issue by kkoscielniak** [OskarGroth/OGSwitch#7]
Hello @OskarGroth, 

I've added `OGSwitch` via Carthage, the `NSView` with custom class `OGSwitch` and I can modify the options of the element, but whatever I try, I cannot see the switch in the storyboard. I'm new in Swift, so probably I have to do something I don't know about. Do you have any idea what might it be? 

Swift v5.0.1, macOS 10.14 Mojave

**Comment by OskarGroth** [comment]
Storyboard inspection is buggy and sometimes break. It's an Xcode issue. It works fine on Xcode 11 Beta.

<img width="805" alt="Skärmavbild 2019-08-27 kl  15 53 21" src="https://user-images.githubusercontent.com/1417019/63777076-ce405f00-c8e2-11e9-88ad-1514f17ac4bb.png">

**Comment by kkoscielniak** [comment]
@OskarGroth I might not be precise before. I can see the switch neither in the storyboard nor in the compiled app itself. 

XCode 10.3
